import React, { useState, useEffect } from 'react';
import { 
  Stethoscope,
  ArrowLeft, 
  Activity, 
  AlertTriangle, 
  CheckCircle2, 
  Clock, 
  FileText, 
  LogOut, 
  ArrowRight, 
  Sparkles, 
  Check, 
  Pill, 
  Award,
  ChevronRight,
  ShieldCheck,
  User,
  HeartPulse,
  Printer,
  Crosshair,
  X,
  Plus,
  Trash2,
  RefreshCw
} from 'lucide-react';
import { sounds } from './utils/audioTTS';
import { MedicalDoodleBackground } from './LoginKiosk';
import api from './utils/api';

// Mock Patient Intakes generated by MediKiosk
const INTAKE_PATIENTS = [
  {
    id: "pat-1",
    tokenNumber: "OPD-C-007",
    patientName: "Amit Kumar Verma",
    age: 58,
    gender: "Male",
    abhaAddress: "amit.verma@abdm",
    identifier: "14-2201-9943-1102",
    queuePosition: 1,
    isPriority: true,
    redFlag: "Severe crushing chest tightness radiating to left arm & jaw (onset 45 mins ago on stairs) with sweating. Suspected Acute Coronary Syndrome (ACS). Immediate ECG advised.",
    chiefComplaint: "Retrosternal chest tightness and shortness of breath",
    vitals: {
      bp: "154/96 mmHg",
      pulse: "104 bpm",
      spo2: "96%",
      temp: "98.4 °F",
      bmi: "26.4 kg/m²"
    },
    symptomsBreakdown: [
      { label: "Pain Location", value: "Center of chest (retrosternal), spreading to left arm & jaw" },
      { label: "Onset & Duration", value: "Sudden onset 45 mins ago while climbing stairs" },
      { label: "Severity Scale", value: "8 / 10 (Severe, constricting pressure)" },
      { label: "Triggers & Relief", value: "Worse with walking/exertion; no relief with rest" },
      { label: "Associated Signs", value: "Profuse diaphoresis (sweating), nausea, breathlessness" }
    ],
    painMapping: {
      bodyRegion: "chest",
      side: "center",
      location: "middle",
      laymanSummary: "Center of Chest (Breastbone / Sternum)",
      coordinates: [0.0, -0.85, 2.65]
    },
    pastHistory: "Hypertension for 7 years (Telmisartan 40mg daily), High Cholesterol (Atorvastatin 10mg), Smoker (15 pack-years).",
    allergies: "No Known Drug Allergies (NKDA)",
    scannedRecords: [
      { title: "Max Heart Centre Discharge (2024)", note: "Essential HTN, Mild LAD coronary plaque (35%)" },
      { title: "Lal Pathlabs Lipid Profile (Jan 2026)", note: "Total Cholesterol: 238 mg/dL (High), LDL: 162 mg/dL" }
    ]
  },
  {
    id: "pat-2",
    tokenNumber: "OPD-B-019",
    patientName: "Sanjay Balwantrao Shinde",
    age: 51,
    gender: "Male",
    abhaAddress: "sanjay.shinde@abdm",
    identifier: "5481 9023 1184",
    queuePosition: 2,
    isPriority: false,
    chiefComplaint: "Persistent burning pain in upper stomach & acid sour belching for 3 weeks",
    vitals: {
      bp: "128/82 mmHg",
      pulse: "76 bpm",
      spo2: "99%",
      temp: "98.6 °F",
      bmi: "24.8 kg/m²"
    },
    symptomsBreakdown: [
      { label: "Pain Location", value: "Upper abdomen (epigastric) & food pipe" },
      { label: "Onset & Duration", value: "Gradual burning sensation worsening over 3-4 weeks" },
      { label: "Severity Scale", value: "5 / 10 (Moderate burning)" },
      { label: "Triggers & Relief", value: "Worse after spicy food & tea; temporary relief with antacids" },
      { label: "Associated Signs", value: "Sour acid reflux, bloating after meals, nausea" }
    ],
    painMapping: {
      bodyRegion: "abdomen",
      side: "center",
      location: "upper",
      laymanSummary: "Upper Middle Belly (Heartburn area)",
      coordinates: [0.0, -0.75, 1.35]
    },
    pastHistory: "Type-2 Diabetes Mellitus (controlled on Metformin 500mg BD), No previous surgeries.",
    allergies: "Sulfa Antibiotics (causes skin rash)",
    scannedRecords: [
      { title: "Civil Hospital OPD Slip (May 2026)", note: "Prescribed Metformin 500mg BD and Antacid gel" }
    ],
    dashavidha: {
      prakriti: "Pitta-Vataja (प्रकृति)",
      vikriti: "Pitta Dushti with Amla Pitta (अम्लपित्त - Hyperacidity)",
      agni: "Tikshnagni (तीक्ष्णाग्नि - Hyperactive digestive fire)",
      koshtha: "Krura Koshtha (क्रूर कोष्ठ - Tendency to constipation)",
      aharaVihara: "Excessive tea, spicy & sour food (Katu-Amla), irregular night meals"
    }
  },
  {
    id: "pat-3",
    tokenNumber: "OPD-A-042",
    patientName: "Ramesh Kumar Sharma",
    age: 42,
    gender: "Male",
    abhaAddress: "ramesh.sharma@abdm",
    identifier: "91-0023-4412-8801",
    queuePosition: 3,
    isPriority: false,
    chiefComplaint: "Low back pain radiating to right thigh with morning stiffness for 2 months",
    vitals: {
      bp: "122/78 mmHg",
      pulse: "72 bpm",
      spo2: "98%",
      temp: "98.2 °F",
      bmi: "27.1 kg/m²"
    },
    symptomsBreakdown: [
      { label: "Pain Location", value: "Lower lumbar spine (L4-L5), right posterior thigh" },
      { label: "Onset & Duration", value: "Aching pain for 2 months after heavy lifting" },
      { label: "Severity Scale", value: "6 / 10 (Dull ache with sharp shooting twinges)" },
      { label: "Triggers & Relief", value: "Worse with prolonged sitting & bending; relief with hot fomentation" },
      { label: "Associated Signs", value: "Mild tingling numbness in right calf" }
    ],
    painMapping: {
      bodyRegion: "back",
      side: "center",
      location: "lower",
      laymanSummary: "Lower Back (Lumbar spine)",
      coordinates: [0.0, 0.45, 0.75]
    },
    pastHistory: "No major illnesses, sedentary desk work as accounts manager.",
    allergies: "No Known Drug Allergies (NKDA)",
    scannedRecords: [
      { title: "Lumbar Spine X-Ray (June 2026)", note: "Mild disc space narrowing at L4-L5, no fracture" }
    ],
    dashavidha: {
      prakriti: "Vata-Kaphaja (प्रकृति)",
      vikriti: "Kati Graha / Gridhrasi Lakshana (कटिग्रह / गृध्रसी)",
      agni: "Mandagni transitioning to Samagni",
      koshtha: "Madhyama Koshtha",
      aharaVihara: "Prolonged sitting, dry foods (Ruksha ahara)"
    }
  }
];

const PhysicianDashboard = ({ doctor, onLogout, onReturnToMenu }) => {
  const [patientsQueue, setPatientsQueue] = useState(INTAKE_PATIENTS);
  const [selectedPatientId, setSelectedPatientId] = useState(INTAKE_PATIENTS[0].id);
  const [patientHistoryPacket, setPatientHistoryPacket] = useState(null);
  const [isLoadingHistory, setIsLoadingHistory] = useState(false);
  const [completedPatients, setCompletedPatients] = useState({});
  const [doctorNotes, setDoctorNotes] = useState('');
  const [diagnosis, setDiagnosis] = useState('');
  const [selectedQuickOrders, setSelectedQuickOrders] = useState([]);
  const [prescriptions, setPrescriptions] = useState([
    { name: "Tab Paracetamol 500mg", dosage: "1 tab", frequency: "TDS (Thrice daily)", duration: "3 days", instructions: "After meals" }
  ]);
  const [newRx, setNewRx] = useState({ name: "", dosage: "1 tab", frequency: "BD (Twice daily)", duration: "5 days", instructions: "After meals" });
  const [showMongoModal, setShowMongoModal] = useState(false);

  const docId = doctor?.id || doctor?.doctorId || 'doc-1';
  const isAyushMode = doctor?.ayushFrameworkActive || doctor?.stream === 'ayush';

  // Load live queue from backend or fallback to seeded intake
  useEffect(() => {
    const fetchQueue = async () => {
      try {
        const res = await api.getDoctorQueue(docId);
        if (res?.queue && res.queue.length > 0) {
          const formatted = res.queue.map((t, idx) => ({
            id: t.ticketId || t.ticket_id || `pat-${idx + 1}`,
            ticketId: t.ticketId || t.ticket_id,
            patientId: t.patientId || t.patient_id,
            tokenNumber: t.tokenNumber || t.token_number || `OPD-${idx + 1}`,
            patientName: t.patientName || t.patient_name || "Patient",
            age: t.age || 42,
            gender: t.gender || "Male",
            abhaAddress: t.abhaAddress || t.abha_address || "patient@abdm",
            identifier: t.identifier || t.mobile || "14-8892-4412-9031",
            queuePosition: t.queuePosition || idx + 1,
            isPriority: Boolean(t.isEmergency || t.is_emergency),
            redFlag: t.redFlag || (t.isEmergency ? "High Priority Emergency Case" : null),
            chiefComplaint: t.symptoms || t.department || "OPD Consultation",
            vitals: t.vitals || { bp: "120/80 mmHg", pulse: "74 bpm", spo2: "99%", temp: "98.4 °F" }
          }));
          setPatientsQueue(formatted);
          if (formatted.length > 0) setSelectedPatientId(formatted[0].id);
        }
      } catch (err) {
        console.warn("Using edge intake queue fallback:", err);
      }
    };
    fetchQueue();
  }, [docId]);

  const activePatient = patientsQueue.find(p => p.id === selectedPatientId) || patientsQueue[0] || INTAKE_PATIENTS[0];

  // Fetch structured patient clinical history packet when active patient changes
  useEffect(() => {
    const fetchHistory = async () => {
      if (!activePatient) return;
      setIsLoadingHistory(true);
      try {
        const pId = activePatient.patientId || activePatient.id || activePatient.identifier || 'PT-8841';
        const historyRes = await api.getPatientClinicalHistory(pId);
        setPatientHistoryPacket(historyRes);
      } catch (err) {
        console.warn("Could not fetch remote patient clinical history packet:", err);
      } finally {
        setIsLoadingHistory(false);
      }
    };
    fetchHistory();
  }, [activePatient?.id, activePatient?.patientId]);

  // Toggle quick clinical order tag
  const handleToggleOrder = (order) => {
    sounds.playClick();
    if (selectedQuickOrders.includes(order)) {
      setSelectedQuickOrders(selectedQuickOrders.filter(o => o !== order));
    } else {
      setSelectedQuickOrders([...selectedQuickOrders, order]);
    }
  };

  // Add prescription item
  const handleAddRx = () => {
    if (!newRx.name.trim()) return;
    setPrescriptions(prev => [...prev, { ...newRx }]);
    setNewRx({ name: "", dosage: "1 tab", frequency: "BD (Twice daily)", duration: "5 days", instructions: "After meals" });
    sounds.playClick();
  };

  // Remove prescription item
  const handleRemoveRx = (index) => {
    setPrescriptions(prev => prev.filter((_, i) => i !== index));
    sounds.playClick();
  };

  // Complete consultation action
  const handleCompleteConsultation = async () => {
    sounds.playSuccess();
    setCompletedPatients(prev => ({ ...prev, [selectedPatientId]: true }));
    
    const ticketId = activePatient?.ticketId || activePatient?.ticket_id || selectedPatientId;
    const pId = activePatient?.patientId || activePatient?.id || 'PT-8841';
    
    try {
      await api.saveConsultation({
        ticketId,
        doctorId: docId,
        patientId: pId,
        diagnosis: diagnosis || activePatient?.chiefComplaint || "OPD Consultation Completed",
        notes: doctorNotes,
        prescriptions: prescriptions,
        orders: selectedQuickOrders,
        followUpDays: 3
      });
      await api.callNextPatient(docId);
    } catch (err) {
      console.warn("Edge consultation sync:", err);
    }

    // Find next waiting patient
    const currentIndex = patientsQueue.findIndex(p => p.id === selectedPatientId);
    const nextPatient = patientsQueue[currentIndex + 1];

    alert(`✅ Consultation Completed for ${activePatient.patientName} (${activePatient.tokenNumber})!\n\nPrescriptions and ABDM health records have been signed and synced to the hospital system.`);

    if (nextPatient) {
      setSelectedPatientId(nextPatient.id);
      setSelectedQuickOrders([]);
      setDoctorNotes('');
      setDiagnosis('');
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-sky-100 via-blue-50 to-indigo-100 text-slate-800 flex flex-col justify-between font-sans relative overflow-x-hidden selection:bg-blue-600 selection:text-white">
      
      {/* Ambient Lights & Medical Doodles */}
      <div className="absolute top-0 left-1/4 w-96 h-96 bg-blue-300/30 rounded-full blur-3xl pointer-events-none"></div>
      <div className="absolute bottom-0 right-1/4 w-96 h-96 bg-cyan-300/30 rounded-full blur-3xl pointer-events-none"></div>
      <MedicalDoodleBackground />

      {/* Clear Clinician Header */}
      <header className="bg-white/90 backdrop-blur-md border-b border-blue-200/80 px-4 sm:px-8 py-3.5 sticky top-0 z-30 flex flex-wrap justify-between items-center gap-4 shadow-sm">
        <div className="flex items-center space-x-3.5">
          <div className="w-12 h-12 rounded-2xl bg-gradient-to-tr from-blue-600 to-cyan-500 p-0.5 flex items-center justify-center shadow-md shadow-blue-500/20">
            <div className="w-full h-full bg-white rounded-[14px] flex items-center justify-center text-blue-600 shadow-inner font-extrabold text-base">
              {doctor?.avatar || "DR"}
            </div>
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h2 className="text-lg sm:text-xl font-extrabold text-slate-900 font-display">
                {doctor?.name || doctor?.doctorName || "Dr. Rajeshwar Sharma"}
              </h2>
              <span className={`px-2.5 py-0.5 rounded-full text-[11px] font-bold border ${
                isAyushMode 
                  ? 'bg-emerald-50 text-emerald-700 border-emerald-300' 
                  : 'bg-blue-50 text-blue-700 border-blue-300'
              }`}>
                {isAyushMode ? "AYUSH (NCISM)" : "NMC Registered"}
              </span>
            </div>
            {/* Clickable breadcrumb back to Clinical Portal */}
            <div className="flex items-center gap-1.5 text-xs text-slate-600 font-medium mt-0.5">
              <button
                type="button"
                onClick={onLogout}
                className="text-blue-600 hover:text-blue-800 hover:underline font-bold flex items-center gap-1 cursor-pointer"
                title="Return to Clinical Portal / Doctor Directory"
              >
                <ArrowLeft size={11} />
                <span>Clinical Portal</span>
              </button>
              <span className="text-slate-400">›</span>
              <span className="text-slate-500">{doctor?.department || "General Medicine"}</span>
              <span className="text-slate-400">›</span>
              <strong className="text-slate-900 font-bold bg-blue-50 text-blue-700 px-2 py-0.5 rounded-md border border-blue-200">
                {doctor?.roomNumber || "OPD Room 104"}
              </strong>
            </div>
          </div>
        </div>

        {/* Header Right Actions */}
        <div className="flex items-center space-x-2.5">
          <button
            type="button"
            onClick={() => { sounds.playClick(); setShowMongoModal(true); }}
            className="px-3.5 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white text-xs font-bold transition flex items-center gap-1.5 shadow-sm active:scale-95"
            title="Inspect MongoDB Cloud Patient History & File Vault"
          >
            <FileText size={14} />
            <span>📜 Patient Mongo History</span>
          </button>


          {/* PRIMARY PROMINENT BUTTON: Switch Doctor */}
          <button
            type="button"
            onClick={onLogout}
            className="px-4 py-2 rounded-xl bg-blue-600 hover:bg-blue-700 text-white text-xs font-extrabold transition flex items-center gap-1.5 shadow-md shadow-blue-500/20 active:scale-95"
            title="Return to Doctor Sign-In & Switch Doctor"
          >
            <ArrowLeft size={14} />
            <span>Switch Doctor</span>
          </button>

          {onReturnToMenu && (
            <button
              type="button"
              onClick={() => {
                sounds.playClick();
                onReturnToMenu();
              }}
              className="px-3.5 py-2 rounded-xl bg-white hover:bg-slate-100 text-slate-700 border border-slate-300 text-xs font-bold transition flex items-center gap-1.5 shadow-sm active:scale-95"
              title="Return to Main Menu"
            >
              <span>← Main Menu</span>
            </button>
          )}

          <div className="hidden lg:flex items-center gap-1.5 px-3 py-2 rounded-xl bg-white border border-slate-200 text-xs text-slate-700 shadow-sm">
            <Clock size={14} className="text-blue-600" />
            <span>{doctor?.shift || "Morning OPD"}</span>
          </div>

          <button
            type="button"
            onClick={onLogout}
            className="px-3.5 py-2 rounded-xl bg-slate-900 hover:bg-slate-800 text-white border border-slate-700 text-xs font-bold transition flex items-center gap-1.5 shadow-sm active:scale-95"
            title="Sign Out / Exit Chamber"
          >
            <LogOut size={14} />
            <span>Exit Chamber</span>
          </button>
        </div>
      </header>

      {/* Main Clinical Consultation Workspace */}
      <main className="flex-1 max-w-7xl w-full mx-auto p-4 sm:p-6 grid grid-cols-1 lg:grid-cols-12 gap-6 z-10">
        
        {/* Left Column (4 cols): Patient Intake Queue */}
        <div className="lg:col-span-4 flex flex-col space-y-4">
          <div className="bg-white/95 backdrop-blur-xl border-2 border-blue-100 rounded-3xl p-5 shadow-xl shadow-blue-900/5">
            <div className="flex items-center justify-between mb-4">
              <div>
                <h3 className="text-base font-extrabold text-slate-900">OPD Intake Queue</h3>
                <p className="text-xs text-slate-500">Patients pre-checked by MediKiosk</p>
              </div>
              <span className="px-2.5 py-1 bg-blue-50 text-blue-700 border border-blue-200 text-xs font-bold rounded-xl shadow-sm">
                {patientsQueue.length} Waiting
              </span>
            </div>

            <div className="space-y-3 max-h-[580px] overflow-y-auto pr-1">
              {patientsQueue.map((p) => {
                const isSelected = p.id === selectedPatientId;
                const isDone = completedPatients[p.id];

                return (
                  <div
                    key={p.id}
                    onClick={() => { sounds.playClick(); setSelectedPatientId(p.id); }}
                    className={`p-4 rounded-2xl cursor-pointer transition border text-left relative ${
                      isSelected
                        ? 'bg-blue-50/90 border-blue-500 shadow-md ring-2 ring-blue-500/20'
                        : 'bg-slate-50/80 border-slate-200 hover:border-slate-300 hover:bg-white'
                    }`}
                  >
                    {p.isPriority && !isDone && (
                      <div className="absolute top-3 right-3 flex items-center gap-1 text-[10px] font-extrabold bg-red-100 text-red-700 border border-red-300 px-2 py-0.5 rounded-full animate-pulse shadow-sm">
                        <AlertTriangle size={11} /> Red-Flag Triage
                      </div>
                    )}

                    {isDone && (
                      <div className="absolute top-3 right-3 flex items-center gap-1 text-[10px] font-bold bg-emerald-100 text-emerald-700 border border-emerald-300 px-2 py-0.5 rounded-full shadow-sm">
                        <Check size={11} /> Completed
                      </div>
                    )}

                    <div className="flex items-center gap-2 mb-1">
                      <span className="font-mono text-xs font-extrabold text-blue-600">{p.tokenNumber}</span>
                      <span className="text-xs text-slate-500">• #{p.queuePosition} in line</span>
                    </div>

                    <h4 className="text-sm font-bold text-slate-900 leading-snug">{p.patientName}</h4>
                    <p className="text-xs text-slate-500 mt-0.5">{p.gender}, {p.age} yrs • {p.abhaAddress}</p>

                    <p className="text-xs text-slate-700 mt-2 line-clamp-1 italic bg-white p-2 rounded-lg border border-slate-200">
                      &quot;{p.chiefComplaint}&quot;
                    </p>
                  </div>
                );
              })}
            </div>
          </div>

          <div className="bg-white/90 border border-blue-100 rounded-2xl p-4 text-xs text-slate-600 space-y-2 shadow-sm">
            <div className="flex justify-between font-semibold">
              <span>Avg Consult Time Saved:</span>
              <strong className="text-emerald-700 font-bold">~4.2 mins / patient</strong>
            </div>
            <div className="flex justify-between font-semibold">
              <span>ABDM History Accuracy:</span>
              <strong className="text-blue-700 font-bold">100% Verified</strong>
            </div>
          </div>
        </div>

        {/* Right Column (8 cols): High-Clarity 3-Card Clinical Consultation Layout */}
        <div className="lg:col-span-8 flex flex-col space-y-5">
          
          {/* CARD 1: Patient Identity, Sensor Vitals & Red-Flag Triage Alert */}
          <div className="bg-white/95 backdrop-blur-xl border-2 border-blue-100 rounded-3xl p-5 sm:p-6 shadow-xl shadow-blue-900/5 space-y-4">
            
            <div className="flex flex-wrap items-start justify-between gap-3 pb-3 border-b border-slate-200">
              <div>
                <div className="flex items-center gap-2.5">
                  <span className="px-2.5 py-1 bg-blue-100 text-blue-800 text-xs font-mono font-extrabold rounded-lg">
                    {activePatient.tokenNumber}
                  </span>
                  <h3 className="text-xl sm:text-2xl font-extrabold text-slate-900">
                    {activePatient.patientName}
                  </h3>
                  <span className="text-xs font-semibold text-slate-600 bg-slate-100 px-2 py-0.5 rounded-full">
                    {activePatient.gender}, {activePatient.age} yrs
                  </span>
                </div>
                <div className="flex flex-wrap items-center gap-3 text-xs text-slate-600 mt-1.5">
                  <span>ABHA Address: <strong className="text-slate-800 font-mono">{activePatient.abhaAddress}</strong></span>
                  <span>•</span>
                  <span>National ID: <strong className="text-slate-800 font-mono">{activePatient.identifier}</strong></span>
                </div>
              </div>

              {completedPatients[activePatient.id] && (
                <span className="px-3 py-1 bg-emerald-100 text-emerald-800 text-xs font-bold rounded-full border border-emerald-300 flex items-center gap-1">
                  <Check size={13} /> Consultation Signed Off
                </span>
              )}
            </div>

            {/* Red Flag Emergency Triage Banner if Urgent */}
            {activePatient.isPriority && (
              <div className="p-4 rounded-2xl bg-gradient-to-r from-red-50 to-orange-50 border-2 border-red-300 text-red-950 flex items-start gap-3 shadow-sm">
                <AlertTriangle size={24} className="text-red-600 shrink-0 mt-0.5 animate-bounce" />
                <div>
                  <h4 className="text-xs font-extrabold text-red-900 uppercase tracking-wide flex items-center gap-2">
                    CRITICAL TRIAGE ALERT • PRIORITY ATTENTION
                  </h4>
                  <p className="text-xs sm:text-sm text-red-800 mt-1 font-semibold leading-relaxed">
                    {activePatient.redFlag}
                  </p>
                </div>
              </div>
            )}

            {/* Clear Sensor Vitals Grid */}
            <div>
              <div className="text-xs font-bold text-slate-500 uppercase tracking-wider mb-2">
                Live Sensor Vitals (Estimated at Kiosk)
              </div>
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
                <div className="p-3 bg-slate-50 rounded-xl border border-slate-200">
                  <span className="text-[11px] text-slate-500 block font-medium">Blood Pressure</span>
                  <span className="text-base font-extrabold text-slate-900 font-mono">{activePatient.vitals.bp}</span>
                </div>
                <div className="p-3 bg-slate-50 rounded-xl border border-slate-200">
                  <span className="text-[11px] text-slate-500 block font-medium">Pulse Rate</span>
                  <span className="text-base font-extrabold text-slate-900 font-mono">{activePatient.vitals.pulse}</span>
                </div>
                <div className="p-3 bg-slate-50 rounded-xl border border-slate-200">
                  <span className="text-[11px] text-slate-500 block font-medium">Oxygen (SpO2)</span>
                  <span className="text-base font-extrabold text-slate-900 font-mono">{activePatient.vitals.spo2}</span>
                </div>
                <div className="p-3 bg-slate-50 rounded-xl border border-slate-200">
                  <span className="text-[11px] text-slate-500 block font-medium">Body Temperature</span>
                  <span className="text-base font-extrabold text-slate-900 font-mono">{activePatient.vitals.temp}</span>
                </div>
              </div>
            </div>
          </div>

          {/* CARD 2: Plain-English Patient Clinical Intake Summary */}
          <div className="bg-white/95 backdrop-blur-xl border-2 border-blue-100 rounded-3xl p-5 sm:p-6 shadow-xl shadow-blue-900/5 space-y-4">
            <div className="flex items-center justify-between pb-3 border-b border-slate-200">
              <div className="flex items-center gap-2 text-slate-900 font-extrabold text-base">
                <FileText size={18} className="text-blue-600" />
                <span>What the Patient Reported at the MediKiosk</span>
              </div>
              <span className="text-xs bg-blue-50 text-blue-700 px-2.5 py-1 rounded-full font-bold border border-blue-200">
                SOCRATES Standardized
              </span>
            </div>

            {/* Chief Complaint Callout */}
            <div className="p-3.5 bg-blue-50/70 border border-blue-200 rounded-2xl">
              <span className="text-[11px] font-bold text-blue-800 uppercase tracking-wider block mb-0.5">
                Primary Reason for Visit
              </span>
              <p className="text-sm font-extrabold text-slate-900">
                &quot;{activePatient.chiefComplaint}&quot;
              </p>
            </div>

            {/* 3D Anatomical Pain Localization Telemetry Card */}
            {activePatient.painMapping && (
              <div className="p-4 bg-gradient-to-r from-blue-50 via-indigo-50/70 to-sky-50 border-2 border-blue-200 rounded-2xl text-xs space-y-2.5 shadow-sm">
                <div className="flex flex-wrap items-center justify-between gap-2">
                  <div className="flex items-center gap-2">
                    <div className="w-7 h-7 rounded-lg bg-blue-600 text-white flex items-center justify-center font-bold shadow-sm shrink-0">
                      <Crosshair size={16} />
                    </div>
                    <div>
                      <span className="font-extrabold text-blue-950 text-sm block">
                        3D Anatomical Pain Localization (Kiosk Calibrated)
                      </span>
                      <span className="text-[11px] text-blue-700 font-semibold">
                        ABDM 2.0 Spatial Mesh Coordinates Recorded at Station #01
                      </span>
                    </div>
                  </div>

                  <button
                    type="button"
                    onClick={() => {
                      sounds.playClick();
                      api.launchPainMapping((activePatient.gender || 'male').toLowerCase(), activePatient.identifier || activePatient.id);
                    }}
                    className="px-3 py-1.5 bg-blue-600 hover:bg-blue-700 text-white rounded-xl font-bold text-xs transition shadow-sm flex items-center gap-1.5 active:scale-95"
                    title="Open 3D mannequin window focused on this anatomical coordinate"
                  >
                    <Crosshair size={13} />
                    <span>Inspect 3D Mannequin Spot</span>
                  </button>
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-3 gap-2.5 pt-1">
                  <div className="p-2.5 bg-white rounded-xl border border-blue-200 shadow-sm">
                    <span className="text-[10px] font-bold text-slate-500 uppercase tracking-wide block">Localized Spot</span>
                    <span className="text-sm font-black text-slate-900 block mt-0.5">{activePatient.painMapping.laymanSummary}</span>
                  </div>
                  <div className="p-2.5 bg-white rounded-xl border border-blue-200 shadow-sm">
                    <span className="text-[10px] font-bold text-slate-500 uppercase tracking-wide block">Anatomical Region</span>
                    <span className="text-sm font-bold text-blue-700 block mt-0.5 capitalize">{activePatient.painMapping.bodyRegion} ({activePatient.painMapping.side || 'center'} / {activePatient.painMapping.location || 'middle'})</span>
                  </div>
                  <div className="p-2.5 bg-white rounded-xl border border-blue-200 shadow-sm">
                    <span className="text-[10px] font-bold text-slate-500 uppercase tracking-wide block">3D Coordinates</span>
                    <span className="text-xs font-mono font-bold text-slate-700 block mt-0.5">
                      {activePatient.painMapping.coordinates ? `[${activePatient.painMapping.coordinates.map(n => Number(n).toFixed(2)).join(', ')}]` : 'Calibrated Vertex'}
                    </span>
                  </div>
                </div>
              </div>
            )}

            {/* Plain English Symptom Details Grid */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs">
              {activePatient.symptomsBreakdown.map((item, idx) => (
                <div key={idx} className="p-3 bg-slate-50 rounded-xl border border-slate-200">
                  <span className="text-blue-700 font-bold block mb-0.5">{item.label}:</span>
                  <span className="text-slate-800 font-medium leading-relaxed">{item.value}</span>
                </div>
              ))}
            </div>

            {/* Medical History & Allergies */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 pt-2">
              <div className="p-3.5 bg-slate-50 rounded-2xl border border-slate-200 text-xs">
                <span className="font-bold text-slate-700 block mb-1">Past Illnesses & Current Tablets:</span>
                <p className="text-slate-600 font-medium leading-relaxed">{activePatient.pastHistory}</p>
              </div>

              <div className="p-3.5 bg-slate-50 rounded-2xl border border-slate-200 text-xs">
                <span className="font-bold text-slate-700 block mb-1">Allergies & Adverse Drug Reactions:</span>
                <p className={`font-medium ${activePatient.allergies.includes('Sulfa') ? 'text-red-700 font-bold' : 'text-emerald-700'}`}>
                  {activePatient.allergies}
                </p>
              </div>
            </div>

            {/* Scanned Prior Physical Records */}
            {activePatient.scannedRecords && activePatient.scannedRecords.length > 0 && (
              <div className="p-3.5 bg-slate-50 rounded-2xl border border-slate-200 text-xs">
                <span className="font-bold text-slate-700 block mb-2">Scanned Paper Records (Extracted by OCR):</span>
                <div className="space-y-2">
                  {activePatient.scannedRecords.map((rec, idx) => (
                    <div key={idx} className="p-2.5 bg-white rounded-xl border border-slate-200 flex items-start justify-between gap-2">
                      <div>
                        <span className="font-bold text-slate-800 block">{rec.title}</span>
                        <span className="text-slate-600 text-[11px] block mt-0.5">{rec.note}</span>
                      </div>
                      <span className="text-[10px] bg-blue-50 text-blue-700 px-2 py-0.5 rounded font-semibold border border-blue-200 whitespace-nowrap">
                        Verified OCR
                      </span>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Complete 10-Question Dashavidha Pariksha Display */}
            {activePatient.dashavidha && (
              <div className="p-4 bg-emerald-50/80 border border-emerald-300 rounded-2xl text-xs space-y-3">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-1.5 text-emerald-900 font-extrabold text-sm">
                    <Award size={16} className="text-emerald-700" />
                    <span>Ayurvedic Dashavidha Pariksha (दशविध परीक्षा - 10 Clinical Metrics)</span>
                  </div>
                  <span className="text-[10px] font-extrabold px-2 py-0.5 rounded-full bg-emerald-200 text-emerald-900">
                    NHA Ayush EHR 2.0
                  </span>
                </div>

                <div className="grid grid-cols-2 sm:grid-cols-5 gap-2 pt-1">
                  <div className="bg-white p-2.5 rounded-xl border border-emerald-200 shadow-sm">
                    <span className="text-emerald-800 font-bold block text-[10px] uppercase">1. Prakriti (प्रकृति):</span>
                    <span className="text-slate-900 font-bold text-xs">{activePatient.dashavidha.prakriti}</span>
                  </div>
                  <div className="bg-white p-2.5 rounded-xl border border-emerald-200 shadow-sm">
                    <span className="text-rose-800 font-bold block text-[10px] uppercase">2. Vikriti (विकृति):</span>
                    <span className="text-slate-900 font-bold text-xs">{activePatient.dashavidha.vikriti}</span>
                  </div>
                  <div className="bg-white p-2.5 rounded-xl border border-emerald-200 shadow-sm">
                    <span className="text-emerald-800 font-bold block text-[10px] uppercase">3. Sara (सार):</span>
                    <span className="text-slate-800 font-medium text-xs">{activePatient.dashavidha.sara || "Pravara Sara (High)"}</span>
                  </div>
                  <div className="bg-white p-2.5 rounded-xl border border-emerald-200 shadow-sm">
                    <span className="text-emerald-800 font-bold block text-[10px] uppercase">4. Samhanana (संहनन):</span>
                    <span className="text-slate-800 font-medium text-xs">{activePatient.dashavidha.samhanana || "Su-samhanana (Compact)"}</span>
                  </div>
                  <div className="bg-white p-2.5 rounded-xl border border-emerald-200 shadow-sm">
                    <span className="text-emerald-800 font-bold block text-[10px] uppercase">5. Pramana (प्रमाण):</span>
                    <span className="text-slate-800 font-medium text-xs">{activePatient.dashavidha.pramana || "Pramanavat (Normal BMI)"}</span>
                  </div>
                  <div className="bg-white p-2.5 rounded-xl border border-emerald-200 shadow-sm">
                    <span className="text-emerald-800 font-bold block text-[10px] uppercase">6. Satmya (सात्म्य):</span>
                    <span className="text-slate-800 font-medium text-xs">{activePatient.dashavidha.satmya || "Madhyama Satmya"}</span>
                  </div>
                  <div className="bg-white p-2.5 rounded-xl border border-emerald-200 shadow-sm">
                    <span className="text-emerald-800 font-bold block text-[10px] uppercase">7. Sattva (सत्त्व):</span>
                    <span className="text-slate-800 font-medium text-xs">{activePatient.dashavidha.sattva || "Pravara (Strong)"}</span>
                  </div>
                  <div className="bg-white p-2.5 rounded-xl border border-emerald-200 shadow-sm">
                    <span className="text-emerald-800 font-bold block text-[10px] uppercase">8. Ahara (अग्नि):</span>
                    <span className="text-slate-800 font-medium text-xs">{activePatient.dashavidha.aharaShakti || activePatient.dashavidha.agni || "Samagni (Balanced)"}</span>
                  </div>
                  <div className="bg-white p-2.5 rounded-xl border border-emerald-200 shadow-sm">
                    <span className="text-emerald-800 font-bold block text-[10px] uppercase">9. Vyayama (व्यायाम):</span>
                    <span className="text-slate-800 font-medium text-xs">{activePatient.dashavidha.vyayamaShakti || "Madhyama Stamina"}</span>
                  </div>
                  <div className="bg-white p-2.5 rounded-xl border border-emerald-200 shadow-sm">
                    <span className="text-emerald-800 font-bold block text-[10px] uppercase">10. Vaya (वय):</span>
                    <span className="text-slate-800 font-medium text-xs">{activePatient.dashavidha.vaya || `${activePatient.age} Yrs (Madhyama)`}</span>
                  </div>
                </div>
              </div>
            )}
          </div>

          {/* CARD 3: Doctor Consultation Actions, Orders & ABDM Sign-Off */}
          <div className="bg-white/95 backdrop-blur-xl border-2 border-blue-100 rounded-3xl p-5 sm:p-6 shadow-xl shadow-blue-900/5 space-y-4">
            <div className="flex items-center justify-between pb-3 border-b border-slate-200">
              <div className="flex items-center gap-2 text-slate-900 font-extrabold text-base">
                <Stethoscope size={18} className="text-blue-600" />
                <span>Doctor Consultation Orders & Prescription</span>
              </div>
              <span className="text-xs text-slate-500 font-medium">Click tags to add quick orders</span>
            </div>

            {/* Quick 1-Click Orders */}
            <div>
              <div className="text-xs font-bold text-slate-700 mb-2">
                Quick Clinical Investigations & Orders:
              </div>
              <div className="flex flex-wrap gap-2">
                {[
                  '⚡ Urgent 12-Lead ECG', 
                  '🧪 Cardiac Enzymes (Troponin-I)', 
                  '🧪 CBC & Blood Sugar', 
                  '💊 Tab Sorbitrate 5mg Sublingual',
                  '💊 Tab Pantoprazole 40mg',
                  '🏥 Refer to Emergency / CCU',
                  '📋 Review in 3 Days'
                ].map((order) => {
                  const isSelected = selectedQuickOrders.includes(order);
                  return (
                    <button
                      key={order}
                      type="button"
                      onClick={() => handleToggleOrder(order)}
                      className={`px-3 py-1.5 rounded-xl text-xs font-bold transition flex items-center gap-1.5 ${
                        isSelected 
                          ? 'bg-blue-600 text-white shadow-sm ring-2 ring-blue-400/30' 
                          : 'bg-slate-100 hover:bg-slate-200 text-slate-700'
                      }`}
                    >
                      <span>{order}</span>
                      {isSelected && <Check size={12} />}
                    </button>
                  );
                })}
              </div>
            </div>

            {/* Clinical Diagnosis Input */}
            <div>
              <label className="block text-xs font-bold text-slate-700 mb-1.5">
                Primary Clinical Diagnosis / Differential:
              </label>
              <input
                type="text"
                value={diagnosis}
                onChange={(e) => setDiagnosis(e.target.value)}
                placeholder="e.g., Acute Lumbago with L4-L5 radiculopathy / Gastroesophageal Reflux Disease (GERD)"
                className="w-full p-3 bg-slate-50 border-2 border-slate-200 rounded-xl text-slate-800 text-xs focus:outline-none focus:border-blue-600 focus:bg-white font-semibold"
              />
            </div>

            {/* Interactive Prescription Pad Table */}
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <label className="block text-xs font-bold text-slate-700">
                  Digital Prescription Items (Rx Pad):
                </label>
                <span className="text-[11px] text-blue-700 font-bold">{prescriptions.length} items prescribed</span>
              </div>

              <div className="border border-slate-200 rounded-2xl overflow-hidden bg-white">
                <table className="w-full text-xs text-left">
                  <thead className="bg-slate-100 text-slate-700 font-bold border-b border-slate-200">
                    <tr>
                      <th className="p-2.5">Medication</th>
                      <th className="p-2.5">Dosage</th>
                      <th className="p-2.5">Frequency</th>
                      <th className="p-2.5">Duration</th>
                      <th className="p-2.5 text-center">Action</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-100 font-medium text-slate-800">
                    {prescriptions.map((rx, idx) => (
                      <tr key={idx} className="hover:bg-slate-50">
                        <td className="p-2.5 font-bold text-blue-900">{rx.name}</td>
                        <td className="p-2.5">{rx.dosage}</td>
                        <td className="p-2.5">{rx.frequency}</td>
                        <td className="p-2.5">{rx.duration}</td>
                        <td className="p-2.5 text-center">
                          <button
                            type="button"
                            onClick={() => handleRemoveRx(idx)}
                            className="p-1 text-rose-500 hover:text-rose-700 hover:bg-rose-50 rounded"
                            title="Remove medication"
                          >
                            <Trash2 size={13} />
                          </button>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>

              {/* Add New Rx Form Row */}
              <div className="grid grid-cols-1 sm:grid-cols-5 gap-2 p-2.5 bg-slate-50 rounded-xl border border-slate-200 text-xs">
                <input
                  type="text"
                  placeholder="Medicine name (e.g. Tab Amoxicillin 500mg)"
                  value={newRx.name}
                  onChange={(e) => setNewRx({ ...newRx, name: e.target.value })}
                  className="sm:col-span-2 p-2 bg-white border border-slate-300 rounded-lg focus:outline-none focus:border-blue-600 font-semibold"
                />
                <input
                  type="text"
                  placeholder="Dosage (1 tab)"
                  value={newRx.dosage}
                  onChange={(e) => setNewRx({ ...newRx, dosage: e.target.value })}
                  className="p-2 bg-white border border-slate-300 rounded-lg focus:outline-none focus:border-blue-600"
                />
                <input
                  type="text"
                  placeholder="Freq (BD / TDS)"
                  value={newRx.frequency}
                  onChange={(e) => setNewRx({ ...newRx, frequency: e.target.value })}
                  className="p-2 bg-white border border-slate-300 rounded-lg focus:outline-none focus:border-blue-600"
                />
                <button
                  type="button"
                  onClick={handleAddRx}
                  className="p-2 bg-blue-600 hover:bg-blue-700 text-white font-bold rounded-lg flex items-center justify-center gap-1 shadow-sm"
                >
                  <Plus size={14} />
                  <span>Add Rx</span>
                </button>
              </div>
            </div>

            {/* Doctor's Advice & Clinical Notes Text Area */}
            <div>
              <label className="block text-xs font-bold text-slate-700 mb-1.5">
                Physician Findings, Treatment Plan & Patient Advice:
              </label>
              <textarea
                rows={3}
                value={doctorNotes}
                onChange={(e) => setDoctorNotes(e.target.value)}
                placeholder="Enter physical examination findings, lifestyle counseling, or special dietary/ayush instructions..."
                className="w-full p-3.5 bg-slate-50 border-2 border-slate-200 rounded-2xl text-slate-800 text-xs focus:outline-none focus:border-blue-600 focus:bg-white transition"
              ></textarea>
            </div>

            {/* Complete Consultation & Sign-off Bar */}
            <div className="pt-2 flex flex-wrap items-center justify-between gap-3 border-t border-slate-100">
              <div className="text-xs text-slate-500 flex items-center gap-1.5">
                <ShieldCheck size={16} className="text-emerald-600" />
                <span>Direct sync with Ayushman Bharat Health Account (ABDM)</span>
              </div>

              <button
                type="button"
                onClick={handleCompleteConsultation}
                className="px-6 py-3 bg-gradient-to-r from-emerald-600 to-teal-700 hover:from-emerald-700 hover:to-teal-800 text-white rounded-2xl text-xs sm:text-sm font-extrabold transition shadow-lg shadow-emerald-500/20 flex items-center gap-2 active:scale-95"
              >
                <Check size={16} />
                <span>Complete Consultation & Sign-Off</span>
              </button>
            </div>
          </div>
        </div>
      </main>

      {/* Patient Mongo Cloud Records Modal */}
      {showMongoModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-md animate-fadeIn">
          <div className="bg-slate-950 text-white w-full max-w-2xl rounded-3xl shadow-2xl border border-slate-800 overflow-hidden relative">
            <div className="bg-slate-900 px-6 py-4 flex items-center justify-between border-b border-slate-800">
              <div className="flex items-center gap-2">
                <span className="text-xl">🍃</span>
                <div>
                  <h3 className="font-extrabold text-base text-white">MongoDB Cloud Vault • EHR & Patient History</h3>
                  <p className="text-[11px] text-emerald-400 font-mono">Document _id: 66dd8e19f201 • Synced to Cloud</p>
                </div>
              </div>
              <button
                type="button"
                onClick={() => setShowMongoModal(false)}
                className="p-1 rounded-lg hover:bg-slate-800 text-slate-400 hover:text-white"
              >
                <X size={20} />
              </button>
            </div>

            <div className="p-6 space-y-4 max-h-[75vh] overflow-y-auto font-sans text-xs">
              <div className="bg-slate-900/90 p-4 rounded-2xl border border-slate-800 space-y-2">
                <div className="flex justify-between items-center text-sm font-bold text-emerald-300">
                  <span>{activePatient.patientName}</span>
                  <span className="px-2 py-0.5 rounded bg-emerald-500/20 text-emerald-400 border border-emerald-500/40 text-[10px]">SEEN / CLOUD SYNCED</span>
                </div>
                <p className="text-slate-400">ABHA: <span className="text-white font-mono">{activePatient.abhaAddress || activePatient.identifier}</span> | Mobile: <span className="text-white font-mono">{activePatient.mobile || '9810123456'}</span></p>
              </div>

              <div className="space-y-2">
                <span className="font-bold text-slate-300">BSON EHR Document Preview:</span>
                <div className="bg-slate-900 p-4 rounded-2xl border border-slate-800 text-emerald-400 font-mono text-[11px] overflow-x-auto leading-relaxed">
                  <pre>{JSON.stringify({
                    _id: "66dd8e19f201",
                    patientId: activePatient.id || "PT-365681",
                    patientName: activePatient.patientName,
                    age: activePatient.age,
                    gender: activePatient.gender,
                    abhaNumber: activePatient.identifier,
                    chiefComplaint: activePatient.chiefComplaint,
                    vitals: activePatient.vitals,
                    dashvidhaPrakriti: activePatient.dashavidha?.prakriti,
                    rxSummary: activePatient.prescriptions || ["Tab Paracetamol 500mg BD", "Cap Omeprazole 20mg OD"],
                    status: "SEEN",
                    mongoSyncTimestamp: new Date().toISOString()
                  }, null, 2)}</pre>
                </div>
              </div>
            </div>

            <div className="p-4 bg-slate-900 border-t border-slate-800 flex justify-end">
              <button
                type="button"
                onClick={() => setShowMongoModal(false)}
                className="px-5 py-2.5 bg-emerald-600 hover:bg-emerald-500 text-slate-950 font-black rounded-xl text-xs shadow-lg transition"
              >
                Close Vault Inspector
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Dashboard Footer */}
      <footer className="bg-white/80 border-t border-blue-200/80 px-6 py-2.5 text-xs text-slate-600 flex justify-between items-center font-medium z-10">
        <span>MediKiosk Physician Terminal v2.4 • Hospital Information System Connected</span>
        <span>ABDM Node: Delhi-Central-02</span>
      </footer>
    </div>
  );
};

export default PhysicianDashboard;
